config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'}
  root to: 'groupbuys#welcome'

  post '/wishlists/:id/toggle_groupbuy' => 'wishlists#toggle_groupbuy', as: :toggle_wishlist_groupbuy

  resources :groupbuys
  
  resources :users do 
    resources :wishlists
  end

  resources :categories, only: nil do
    resources :groupbuys, only: :index
  end
  
  # resources :groupbuys do
  #   collection do
  #   end
  # end

  #get 'users/sign_up' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :groupbuys
    has_many :wishlists, through: :groupbuys

    accepts_nested_attributes_for :groupbuys

    validates :name, presence: true, length: {minimum: 3}

    def groupbuy_attributes=(groupbuys)
        #binding.pry
        groupbuys.values.each do |gb_hash|
            self.groupbuys.push(Groupbuy.create(gb_hash))
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category, only: %i[show edit update destroy]
    
    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
        @category.groupbuys.build(name: " ")
    end

    def create
        @category = Category.create(category_params)
        
        if @category.save
          redirect_to @category
        else
          render 'new'
        end
    end
    
    def show
    end
    
    def edit
    end
    
    def update
        if @category.update(category_params)
          redirect_to @category
        else
          render 'edit'
        end
    end
    
    def destroy
        @category.destroy
        flash[:success] = "Category deleted"
        redirect_to categories_url
    end
    
    private

    def set_category
        @category = Category.find(params[:id])
    end
    
    def category_params
        params.require(:category).permit(:name,
          groupbuys_attributes: [
            :item_type,
            :name,
            :start_date,
            :end_date,
            :pricing,
            :sale_type,
            :image
          ])
    end
end

app/views/categories/edit.html.erb
<%# Display validation errors in form %>
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@category.errors.count, "error") %>
      prohibited this category from being saved:
    </h2>
 
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container d-flex flex-column mt-3">
    <div class="row align-items-center justify-content-center no-gutters min-vh-100">
        <div class="col-lg-5 col-md-13 py-8 py-xl-0 mb-4">
            <div class="card shadow">
                <div class="card-body p-6 mb-4">
                  <div class="mb-4">
                    <h1 class="mb-1 font-weight-bold">Edit Category</h1>
                  </div>

                  <%= form_with(model: @category, class: "form") do |f| %>
                        <div class="form-group">
                            <%= f.label :category_name, class: "form-label" %>
                            <%= f.text_field :name, class:"form-control-1" %><br>
                        </div>
                    
                        <%= f.submit %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="pt-lg-8 pt-8 pb-12 bg-primary" id="bootstrap-overrides">
<div class="container">
    <div class="row align-items-center">
        <div class="col-xl-7 col-lg-7 col-md-12">
            <div>
                <h1 class="text-white display-4 font-weight-bold"><%= @category.name %></h1>
                <%= link_to("Edit Category", edit_category_path(@category), class: "btn btn-white", id: "bootstrap-overrides") %>

                <%= button_to "Delete", @category, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-success" %>

            </div>
        </div>
    </div>
</div>
</div>
<div class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 col-lg-9 col-md-8 col-12">
                <div class="row">
                    <% @category.groupbuys.each do |g| %>
                        <div class="col-lg-4">
                            <div class="card mb-4 card-hover">
                                <a href="#!" class="card-img-top">
                                        <img src="<%=g.image%>" alt="" class="card-img-top rounded-top" id="gb-image">
                                </a>
                                <div class="card-body">
                                    <h3 class="h4 mb-2 text-truncate-line-2 ">
                                        <a href="<%= groupbuy_path(g.id) %>" class="text-inherit">
                                        <%= g.name %>
                                        </a>
                                    </h3>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">Start Date:</p> <%= g.start_date %></li>
                                    </ul>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">End Date:</p> <%= g.end_date %></li>
                                    </ul>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">Base Price:</p> <%= '$%.2f' % g.pricing %></li>
                                    </ul>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">Sale Type:</p> <%= g.sale_type %></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>