config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'}
  root to: 'groupbuys#welcome'

  post '/wishlists/:id/toggle_groupbuy' => 'wishlists#toggle_groupbuy', as: :toggle_wishlist_groupbuy

  resources :groupbuys
  
  resources :users do 
    resources :wishlists
  end

  resources :categories, only: nil do
    resources :groupbuys, only: :index
  end
  
  # resources :groupbuys do
  #   collection do
  #   end
  # end

  #get 'users/sign_up' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
    belongs_to :user
    has_many :groupbuys
    has_many :categories, through: :groupbuys

    validates :name, presence: true,
            length: {maximum: 50,
             too_long: "50 characters is the maximum allowed"}
    validates :note, length: {maximum: 400,
              too_long: "400 characters is the maximum allowed"},
            allow_blank: true

    def has_groupbuy?(groupbuy)
      groupbuy.wishlist_id == self.id
    end
    
    def toggle_groupbuy(groupbuy)
      if has_groupbuy?(groupbuy)
        self.groupbuys.delete(groupbuy)
      else
        self.groupbuys.push(groupbuy)
      end
    end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :authenticate_user!, only: [:index, :new, :create]
    
    def index
        @user = User.find_by(params[:id])
        @user_wishlists = @user.wishlists
    end

    def new
        @user = User.find_by(params[:id])
        @wishlist = Wishlist.new    
    end

    def create
        @user = User.find_by(params[:id])
        @wishlist = Wishlist.new(wishlist_params)
        @wishlist.user = @user
        if @wishlist.save
          redirect_to user_wishlists_path(current_user), notice: "Wishlist created successfully."
        else
          render :new
        end
    end

    def show
        @user = current_user
        @wishlist = Wishlist.find_by(id: params[:id])
        render :show
    end

    def edit
        @wishlist = Wishlist.find_by(id: params[:id])
        @user = User.find_by_id(@wishlist.user_id)
    end


  def update
    @wishlist = Wishlist.find_by(id: params[:id])
    @user = User.find_by_id(@wishlist.user_id)
    if @wishlist.update(wishlist_params)
      redirect_to user_wishlists_path(current_user), notice: "Wishlist updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @wishlist = Wishlist.find_by(id: params[:id])
    @user = User.find_by_id(@wishlist.user_id)
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to user_wishlists_path(current_user), notice: 'Wishlist was removed.' }
    end
  end

  def toggle_groupbuy
    @wishlist = Wishlist.find_by_id(params[:wishlist_id])
    @wishlist.toggle_groupbuy(Groupbuy.find_by_id(params[:groupbuy_id]))
    redirect_to groupbuys_path(:wishlist_id => @wishlist.id)
  end
  
  private

  def wishlist_params
    params.require(:wishlist).permit(:name, :note)
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/edit.html.erb
<div class="container d-flex flex-column">
    <div class="row align-items-center justify-content-center no-gutters min-vh-100">
        <div class="col-lg-5 col-md-13 py-8 py-xl-0">
            <div class="card shadow">
                <div class="card-body p-6 mb-4">
                  <div class="mb-4">
                    <h1 class="mb-1 font-weight-bold">Edit Wishlist</h1>
                  </div>
                  <%= form_with(model: [@user, @wishlist], class: "form") do |f| %>
                  
                    <div class="form-group">
                      <%= f.label :name, class: "form-label" %><br />
                      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control-1" %>
                    </div>
                  
                    <div class="form-group">
                      <%= f.label :note, class: "form-label" %>
                      <%= f.text_area :note, autocomplete: "note", class: "form-control-1", size: "70x5" %>
                    </div>
                  
                    <%= f.submit "Update Wishlist", class: "btn btn-primary btn-block" %>
                  
                  <% end %>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/wishlists/index.html.erb
<div class="bg-primary" id="bootstrap-overrides">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-xl-12 col-lg-12 col-md-12 col-12">
          <div class="py-4 py-lg-6">
            <h1 class="mb-0 text-white display-4">My Wishlists</h1>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="py-6 mb-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="row justify-content-between align-items-center">
          <div class="col-xl-8 col-md-6">
            <h4 class="mb-3 mb-md-0">Total <%= Wishlist.all.count %> Wishlists </h4>
          </div>
          <div class="col-xl-2 col-md-3">
            <%= link_to("Create a new wishlist", new_user_wishlist_path(@user), class: "btn-wish") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
        <!-- Card -->
        <% @user_wishlists.each do |w| %>
          <div class="col-xl-4 col-lg-6 col-md-6">
            <div class="card mb-4 card-hover" >
              <div class="d-flex justify-content-between align-items-center p-4">
                <div class="d-flex">
                  <div class="ml-3">
                    <h4 class="mb-1">
                      <%= link_to w.name, user_wishlist_path(@user, id: w.id) %>
                    </h4>
                    <p class="mb-0 font-size-xs">
                      <span class="mr-2">
                        <span class="text-dark font-weight-medium"><%= w.groupbuys.count %></span>
                        Groupbuys
                      </span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
</div>

app/views/wishlists/show.html.erb
<div class="pt-lg-8 pt-8 pb-12 bg-primary">
<div class="container">
    <div class="row align-items-center">
        <div class="col-xl-7 col-lg-7 col-md-12">
            <div>
                <h1 class="text-white display-4 font-weight-bold"><%= @wishlist.name %></h1>
                <p class="text-white-50 lead">
                    <% if !@wishlist.note.blank? %>
                        Note: <%= @wishlist.note %>
                    <% end %>
                </p>
                <%= link_to "Edit wishlist", edit_user_wishlist_path(@user, id: @wishlist.id), class:"btn btn-white" %><br><br>
                <%= button_to "Delete", user_wishlist_path(@user, id: @wishlist.id), method: :delete, class:"btn btn-white", data: {confirm: 'Are you sure?'} %>
            </div>
        </div>
    </div>
</div>
</div>

<div class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 col-lg-9 col-md-8 col-12">
                <div class="row">
                    <% @wishlist.groupbuys.each do |g| %>
                        <div class="col-lg-4">
                            <div class="card mb-4 card-hover">
                                <a href="#!" class="card-img-top">
                                        <img src="<%=g.image%>" alt="" class="card-img-top rounded-top" id="gb-image">
                                </a>
                                <div class="card-body">
                                    <h3 class="h4 mb-2 text-truncate-line-2 ">
                                        <a href="#!" class="text-inherit">
                                        <%= g.name %>
                                        </a>
                                    </h3>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">Start Date:</p> <%= g.start_date %></li>
                                    </ul>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">End Date:</p> <%= g.end_date %></li>
                                    </ul>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">Base Price:</p> <%= '$%.2f' % g.pricing %></li>
                                    </ul>
                                    <ul class="mb-3  list-inline">
                                        <li class="list-inline-item"><p class="boldish">Sale Type:</p> <%= g.sale_type %></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>