config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'}
  root to: 'groupbuys#welcome'

  post '/wishlists/:id/toggle_groupbuy' => 'wishlists#toggle_groupbuy', as: :toggle_wishlist_groupbuy

  resources :groupbuys
  
  resources :users do 
    resources :wishlists
  end

  resources :categories, only: nil do
    resources :groupbuys, only: :index
  end
  
  # resources :groupbuys do
  #   collection do
  #   end
  # end

  #get 'users/sign_up' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/groupbuy.rb
class Groupbuy < ApplicationRecord
    belongs_to :wishlist, optional: true
    belongs_to :category, optional: true

    validates :name, :start_date, :end_date, :pricing, presence: true
    validates :name, length: {minimum: 1}

    # Scope Methods
    scope :filter_by_status, -> (status) { where status: status }
    scope :filter_by_cat, -> (category_id) {where category_id: category_id}

    def self.search(search)
        if search
            where(["name LIKE ?", "%#{search}%"])
        else
            @groupbuys = Groupbuy.all
        end
    end
    
end

app/controllers/groupbuys_controller.rb
class GroupbuysController < ApplicationController
    before_action :authenticate_user!, only: [:index, :new, :create]

    ORDERS = [ "pricing ASC", "pricing DESC", "name ASC", "name DESC" ]

    def welcome
        @groupbuys = Groupbuy.all 
        render :welcome
    end
    
    def index
        @user = current_user
        @user_wishlists = @user.wishlists
        @wishlist = @user_wishlists.find_by(id: params[:wishlist_id])
        @groupbuys = Groupbuy.where(nil) # anonymous scope
        @groupbuys = @groupbuys.search(params[:search]) if params[:search].present?
        @groupbuys = @groupbuys.filter_by_status(params[:status]) if params[:status].present?
        @groupbuys = @groupbuys.filter_by_cat(params[:category_id]) if params[:category_id].present?
        if params[:ordering] && ordering = ORDERS[params[:ordering].to_i]
            @groupbuys = @groupbuys.order(ordering)
        end
        render :browse
    end

    def show
        @groupbuy = Groupbuy.find(params[:id])
        render :show
    end

    private

    def groupbuy_params
        params.require(:groupbuy).permit(:name, :price, :search)
    end

end

app/helpers/groupbuys_helper.rb
module GroupbuysHelper
end

app/views/groupbuys/_groupbuys.html.erb
<script>
    $(document).ready(function(){
    
        $('.like-button').click(function(){
            $(this).toggleClass('is-active');
        })
    
    })
    $.removeClass('hoverCssClass');

    var checkBoxes = document.querySelectorAll(".form-check-input");
    var form = document.querySelector('form');
    
    for (const check of checkBoxes) {
    check.addEventListener( 'change', function() {
      Rails.fire(form, 'submit');
    });
    }
    $(function () {
    $('[data-toggle="popover"]').popover()
    })
</script>

           
<div class="row">
    <% @groupbuys.each do |g|%>
        <div class="col-lg-4">
            <div class="card mb-4 card-hover">
                <a href="<% if current_user %>/groupbuys/<%= g.id %><%end%>" class="card-img-top">
                    <% if g.wishlist_id != nil %>

                            <div href="#" class="heart">
                                <i class="fa fa-heart fa-1x"></i>
                            </div>
                          
                    <% end %>
                    <img src="<%=g.image%>" alt="" class="card-img-top rounded-top" id="gb-image">
                </a>
                <div class="card-body">
                    <h3 class="h4 mb-2 text-truncate-line-2 ">
                        <a href="/groupbuys/<%= g.id %>" class="text-inherit">
                        <%= g.name %>
                        </a>
                    </h3>
                    <ul class="mb-3  list-inline">
                        <li class="list-inline-item"><p class="boldish">Start Date:</p> <%= g.start_date %></li>
                    </ul>
                    <ul class="mb-3  list-inline">
                        <li class="list-inline-item"><p class="boldish">End Date:</p> <%= g.end_date %></li>
                    </ul>
                    <ul class="mb-3  list-inline">
                        <li class="list-inline-item">
                            <% if g.pricing != 0.0 %>
                                <p class="boldish">Base Price:</hp> <%= '$%.2f' % g.pricing %>
                            <% else %>
                                Pricing Not Available
                            <% end %>
                        </li>
                    </ul>
                    <ul class="mb-3  list-inline">
                        <li class="list-inline-item"><p class="boldish">Sale Type:</p> <%= g.sale_type %></li>
                    </ul>
                    <% if @wishlist%>
                        <%= form_tag(toggle_wishlist_groupbuy_url(@user, @wishlist), remote: true) do |f| %>
                            <%= hidden_field_tag :wishlist_id, @wishlist.id %>
                            <%= hidden_field_tag :groupbuy_id, g.id %> 
                        
                            <!-- Button: Add or Remove item from list -->
                            <button id="like">
                                <% if @wishlist.has_groupbuy?(g) %>
                                    <a href="javascript:void(0);" class="like-button is-active">
                                        <i class="material-icons not-liked bouncy">favorite_border</i>
                                        <i class="material-icons is-liked bouncy">favorite</i>
                                        <span class="like-overlay"></span>
                                    </a>
                                <% else %>
                                    <a href="javascript:void(0);" class="like-button">
                                        <i class="material-icons not-liked bouncy">favorite_border</i>
                                        <i class="material-icons is-liked bouncy">favorite</i>
                                        <span class="like-overlay"></span>
                                    </a>
                                <% end %>
                            </button>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/groupbuys/browse.html.erb
<script>
    function changeSelected() { 
        document.getElementById('wishlist_id').selectedIndex=1;

    } 
</script>

<div class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12 mb-4">
                <div class="row d-lg-flex justify-content-between align-items-center">
                    <div class="col-md-6 col-lg-8 col-xl-9 ">
                        <h4 class="mb-3 mb-lg-0">Displaying <%= @groupbuys.count%> Groupbuys </h4>
                    </div>
                    <div class="d-inline-flex col-md-6 col-lg-4 col-xl-3 ">
                        <!-- List  -->
                        <div class="dropdown bootstrap-select" style="width: 100%;">
                            <%= form_with(url: groupbuys_url, method: :get, class: "selectpicker sort-item" ) do |f| %>
                                
                                <select name="wishlist_id" id="wishlist_id">
                                    <!-- Select a Wishlist -->
                                    <option value="0" <%= !@wishlist ? "selected" : "" %>>SELECT A WISHLIST</option>

                                    <% @user_wishlists.each do |w| %>
                                        <option data-sort="<%= w.id %>" value="<%= w.id %>" <%= "#{w.id}" == @wishlist ? "selected" : "" %>><%=w.name%></option>
                                    <% end %>
                                </select>
                                <%= submit_tag('Update') %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-4 mb-4 mb-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h4 class="mb-0">Filter</h4>
                    </div>
                    <div class="card-body">
                        <span class="dropdown-header px-0 mb-2"> Type</span>
                        <!-- Checkbox -->
                        <%= form_tag groupbuys_path, method: :get do %>
                            <div class="custom-control custom-checkbox mb-1">
                                <input type="checkbox" name="category_id[]" value="1" class="custom-control-input" id="reactCheck">
                                <label class="custom-control-label" for="reactCheck">Keyboard</label>
                            </div>
                            <!-- Checkbox -->
                            <div class="custom-control custom-checkbox mb-1">
                                <input type="checkbox" name="category_id[]" value="2" class="custom-control-input" id="javascriptCheck">
                                <label class="custom-control-label" for="javascriptCheck">Keycap</label>
                            </div>
                            <!-- Checkbox -->
                            <div class="custom-control custom-checkbox mb-1">
                                <input type="checkbox" name="category_id[]" value="3" class="custom-control-input" id="angularCheck">
                                <label class="custom-control-label" for="angularCheck">Switch</label>
                            </div>
                        
                    </div>
                    <div class="card-body border-top">
                        <span class="dropdown-header px-0 mb-2"> Status</span>
                        <!-- Checkbox -->
                        
                            <div class="custom-control custom-checkbox mb-1">
                                <input type="checkbox" name="status[]" value="live" class="custom-control-input" id="allTwoCheck">
                                <label class="custom-control-label" for="allTwoCheck">Live</label>
                            </div>
                            <!-- Checkbox -->
                            <div class="custom-control custom-checkbox mb-1">
                                <input type="checkbox" name="status[]" value="upcoming" class="custom-control-input" id="beginnerTwoCheck">
                                <label class="custom-control-label" for="beginnerTwoCheck">Upcoming</label>
                            </div>
                            <!-- Checkbox -->
                            <div class="custom-control custom-checkbox mb-1">
                                <input type="checkbox" name="status[]" value="ic" class="custom-control-input" id="intermediateCheck">
                                <label class="custom-control-label" for="intermediateCheck">Interest Check</label>
                            </div>
                            <!-- Checkbox -->
                            <div class="custom-control custom-checkbox mb-1">
                                <input type="checkbox" name="status[]" value="ended" class="custom-control-input" id="AdvancedTwoCheck">
                                <label class="custom-control-label" for="AdvancedTwoCheck">Ended</label>
                            </div>
                            
                        
                    </div>
                    <div class="card-body border-top">
                            <span class="dropdown-header px-0 mb-2">Sort By</span>
                            <%= select_tag :ordering, options_for_select([['Select', '5'],['Price - Low to High', '0'], ['Price - High to Low', '1'], ['Name - A to Z', '2'], ['Name - Z to A', '3']]), style: "border-color: #dbd8e9 !important;" %>
                            <%= submit_tag "Submit", id:"btn-filter" %>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-9 col-md-8 col-12">
                <%= render "groupbuys" %>
            </div>
        </div>
    </div>
</div>

app/views/groupbuys/welcome.html.erb
<body>
    <div class="bg-primary", id="bootstrap-overrides">
        <div class="container">
            <!-- Hero Section -->
            <div class="row align-items-center no-gutters">
                <div class="col-xl-5 col-lg-6 col-md-13">
                    <div class="py-5 py-lg-0">
                        <h1 class="text-white display-4 font-weight-bold">Welcome to Hoshii!</h1>
                        <p class="text-white-50 mb-4 lead">
                            Stay up-to-date on the latest custom mechanical keyboard groupbuys.
                        </p>
                        <a href="/groupbuys" class="btn btn-white" id="bootstrap-overrides">Browse Groupbuys</a>
                        <a href="<% if user_signed_in? %><%= new_user_wishlist_path(current_user) %><% else %><%= new_user_session_path %><%end%>" class="btn btn-success" id="bootstrap-overrides">Create a Wishlist</a>
                    </div>
                </div>
                <div class=" col-xl-7 col-lg-6 col-md-13 text-lg-right text-center">
                    <img src="assets/keebs3.png" alt="" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
    <div class="bg-white py-4 shadow-sm">
        <div class="container">
            <div class="row align-items-center no-gutters">
                <!-- Features -->
                <div class="col-xl-4 col-lg-4 col-md-6 mb-lg-0 mb-2">
                    <div class="d-flex align-items-center">
                        <span class="icon-sahpe icon-lg bg-light-warning rounded-circle text-center text-dark-warning font-size-md "> <i class="fe fe-video"> </i></span>
                        <div class="ml-3">
                            <h4 class="mb-0 font-weight-semi-bold">Track Live and Upcoming Groupbuys</h4>
                            <p class="mb-0">All Groupbuys in one place</p>
                        </div>
                    </div>
                </div>
                <!-- Features -->
                <div class="col-xl-4 col-lg-4 col-md-6 mb-lg-0 mb-2">
                    <div class="d-flex align-items-center">
                        <span class="icon-sahpe icon-lg bg-light-warning rounded-circle text-center text-dark-warning font-size-md "> <i class="fe fe-users"> </i></span>
                        <div class="ml-3">
                            <h4 class="mb-0 font-weight-semi-bold">Get Notifications</h4>
                            <p class="mb-0">Receive Updates When Groupbuys are Live</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="py-6">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 col-lg-9 col-md-8 col-12 col-13" id="bootstrap-overrides">
                    <%= render "groupbuys" %>
            </div>
        </div>
    </div>
    
</body>