config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'}
  root to: 'groupbuys#welcome'

  post '/wishlists/:id/toggle_groupbuy' => 'wishlists#toggle_groupbuy', as: :toggle_wishlist_groupbuy

  resources :groupbuys
  
  resources :users do 
    resources :wishlists
  end

  resources :categories, only: nil do
    resources :groupbuys, only: :index
  end
  
  # resources :groupbuys do
  #   collection do
  #   end
  # end

  #get 'users/sign_up' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
	<link href="custom.css" rel="stylesheet">
	<script>
		$(document).ready(function(){
			$('.dropdown-toggle').dropdown()
		});
		$('#myModal').modal(options)
	</script>
</head>

<nav class="navbar navbar-expand-lg navbar-default">
	<div class="container-fluid px-0">
		<a class="navbar-brand" href="/" ><img src="/assets/Hoshii2.png" width= "90%" alt=""> </a>
		<!-- Button -->
		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbar-default" aria-controls="navbar-default" aria-expanded="false" aria-label="Toggle navigation">
			<span class="icon-bar top-bar mt-0"></span>
			<span class="icon-bar middle-bar"></span>
			<span class="icon-bar bottom-bar"></span>
		</button>
		<!-- Collapse -->
		<div class="collapse navbar-collapse align-items-center" id="navbar-default">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link", id="bootstrap-overrides", href="/">
						Home
						<span class="sr-only">(current)</span>
					</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link", id="bootstrap-overrides", href="<%= groupbuys_path %>">
						Browse
            			<span class="sr-only">(current)</span>
					</a>
				</li>
        		<li class="nav-item active">
					<a class="nav-link", id="bootstrap-overrides", href="<%= user_wishlists_path(current_user) %>">
						My Wishlists
            			<span class="sr-only">(current)</span>
					</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link", id="bootstrap-overrides", href="<%= categories_path %>">
						Categories
						<span class="sr-only">(current)</span>
					</a>
				</li>
			</ul>
      <%= form_with url: groupbuys_path, method: :get, class: "mt-3 mt-lg-0 ml-lg-3 d-flex align-items-center" do |form| %>
        <span class="position-absolute pl-3 search-icon">
					<i class="fa fa-search"></i>
				</span>
        <%= form.text_field :search, class: "form-control pl-6", id: "bootstrap-overrides", placeholder: "Search Groupbuys" %>
      <% end %>
			<ul class="navbar-nav navbar-right-wrap ml-auto d-none d-lg-block align-items-center">
				<li class="nav-item dropdown dropleft">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">						
						<div class="avatar avatar-md avatar-indicators avatar-online">
							<img alt="avatar" src="/assets/Logo.png" class="rounded-circle shadow border">
						</div>
					</a>
                    <div class="dropdown-menu">
                        <a href="<%= edit_user_registration_path %>" class="dropdown-item">Edit My Account</a>
                        <div class="dropdown-divider"></div>
						<%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "dropdown-item", "data-toggle" => "modal", 'data-target' => '.modal' %>
                    </div>
                </li>
			</ul>
	
		</div>
	</div>
</nav>

<%= render 'users/modal' %>

app/views/layouts/_notnav.html.erb
<nav class="navbar navbar-expand-lg navbar-default">
    <div class="container-fluid px-0">
        <a class="navbar-brand" href="/" ><img src="/assets/Hoshii2.png" width= "90%" alt=""> </a>
        <ul class="navbar-nav navbar-right-wrap ml-auto d-none d-lg-block align-items-center">
            <li class="nav-item active">
            <a class="nav-link", id="bootstrap-overrides", href="<%= new_user_session_path %>">
                Sign In
                <span class="sr-only">(current)</span>
            </a>
            </li>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoshiiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
  rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if user_signed_in? %>
      <%= render "layouts/navbar" %>
    <% else %>
      <%= render "layouts/notnav" %>
    <% end %>

    <%= yield %>
  </body>
</html>